---
- hosts: all
  gather_facts: no
  roles:
    - nkp-checks
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    image_url:                                       # url to download image from nutanix portal 
    IMAGE_NAME:                                      # Image name - corresponding to the above url
    SSH_PUBLIC_KEY:                                  # SSH key of the local machine,used by ansible to connect to the test VM
    NUTANIX_ENDPOINT:                                # Prism Central IP address
    NUTANIX_USER: admin                              # Prism Central username
    NUTANIX_PASSWORD: ''                             # Prism Central password
    NUTANIX_PORT: 9440                               # Prism Central port (default: 9440)                                          
    NUTANIX_PRISM_ELEMENT_CLUSTER_NAME:              # Prism Element cluster name - Ex: PHX-POC207
    CONTROL_SUBNET:                                  # controlplane subnet name
    WORKER_SUBNET:                                   # worker subnet name
    NUTANIX_STORAGE_CONTAINER_NAME:                  # Change to your preferred Prism storage container
